import "./globals.css";
import { Suspense } from "react";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { ourFileRouter } from "@/lib/uploadthing";
import { extractRouterConfig } from "uploadthing/server";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import { OrderNotificationProvider } from "@/components/providers/order-notification-provider";
import { OrderBuzzer } from "@/components/providers/order-buzzer";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LocalBite",
  description: "Generated by create next app",
};

async function SessionAwareContent({ children }: { children: React.ReactNode }) {
  const session = await auth();

  return session?.user?.restaurantId ? (
    <OrderNotificationProvider restaurantId={session.user.restaurantId}>
      {children}
      <OrderBuzzer />
    </OrderNotificationProvider>
  ) : (
    <>{children}</>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col overflow-hidden h-screen">
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />

        <main className="flex-1 overflow-y-auto bg-[#f5f5f5]">
          <Suspense fallback={<>{children}</>}>
            <SessionAwareContent>{children}</SessionAwareContent>
          </Suspense>
        </main>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}